package mediainfo

type AudioTrack struct {
	Type                       string  `json:"@type"`
	ID                         int64   `json:"ID,string"`
	Format                     string  `json:"Format"`
	FormatCommercial           string  `json:"Format_Commercial"`
	FormatProfile              string  `json:"Format_Profile"`
	CodecID                    string  `json:"CodecID"`
	CodecIDInfo                string  `json:"CodecID_Info"`
	Count                      int64   `json:"Count,string"`
	Duration                   float64 `json:"Duration,string"`
	DurationString             string  `json:"Duration/String"`
	DurationString1            string  `json:"Duration/String1"`
	DurationString2            string  `json:"Duration/String2"`
	DurationString3            string  `json:"Duration/String3"`
	DurationString4            string  `json:"Duration/String4"`
	DurationString5            string  `json:"Duration/String5"`
	BitRate                    int64   `json:"BitRate,string"`
	BitRateMode                string  `json:"BitRate_Mode"`
	BitRateModeString          string  `json:"BitRate_Mode_String"`
	Channels                   int64   `json:"Channel(s),string"`
	FrameCount                 int64   `json:"FrameCount,string"`
	FrameRate                  float64 `json:"FrameRate,string"`
	FrameRateString            string  `json:"FrameRate/String"`
	FrameRateMode              string  `json:"FrameRate_Mode"`
	FrameRateModeString        string  `json:"FrameRate_Mode_String"`
	BitDepth                   string  `json:"BitDepth"`
	BitDepthString             string  `json:"BitDepth_String"`
	CompressionMode            string  `json:"Compression_Mode"`
	CompressionModeString      string  `json:"Compression_Mode_String"`
	StreamOrder                int64   `json:"StreamOrder,string"`
	StreamSize                 int64   `json:"StreamSize,string"`
	Language                   string  `json:"Language"`
	Default                    string  `json:"Default"`
	Default_String             string  `json:"Default_String"`
	Forced                     string  `json:"Forced"`
	Forced_String              string  `json:"Forced_String"`
	SamplesPerFrame            int64   `json:"SamplesPerFrame,string"`
	SamplingCount              int64   `json:"SamplingCount,string"`
	SamplingRate               int64   `json:"SamplingRate,string"`
	SamplingRateString         string  `json:"SamplingRate_String"`
	SourceDuration             float64 `json:"Source_Duration,string"`
	SourceDurationString       string  `json:"Source_Duration_String"`
	SourceDurationString1      string  `json:"Source_Duration_String1"`
	SourceDurationString2      string  `json:"Source_Duration_String2"`
	SourceDurationString3      string  `json:"Source_Duration_String3"`
	SourceDurationString5      string  `json:"Source_Duration_String5"`
	SourceFrameCount           int64   `json:"Source_FrameCount,string"`
	SourceStreamSize           int64   `json:"Source_StreamSize,string"`
	SourceStreamSizeProportion float64 `json:"Source_StreamSize_Proportion,string"`
	SourceStreamSizeString     string  `json:"Source_StreamSize_String"`
	SourceStreamSizeString1    string  `json:"Source_StreamSize_String1"`
	SourceStreamSizeString2    string  `json:"Source_StreamSize_String2"`
	SourceStreamSizeString3    string  `json:"Source_StreamSize_String3"`
	SourceStreamSizeString4    string  `json:"Source_StreamSize_String4"`
	SourceStreamSizeString5    string  `json:"Source_StreamSize_String5"`
	StreamCount                int64   `json:"StreamCount,string"`
	StreamKind                 string  `json:"StreamKind"`
	StreamKindID               int64   `json:"StreamKindID,string"`
	StreamKindString           string  `json:"StreamKind_String"`
	StreamSizeProportion       string  `json:"StreamSize_Proportion"`
	StreamSizeString           string  `json:"StreamSize_String"`
	StreamSizeString1          string  `json:"StreamSize_String1"`
	StreamSizeString2          string  `json:"StreamSize_String2"`
	StreamSizeString3          string  `json:"StreamSize_String3"`
	StreamSizeString4          string  `json:"StreamSize_String4"`
	StreamSizeString5          string  `json:"StreamSize_String5"`
	TaggedDate                 string  `json:"Tagged_Date"`
	Title                      string  `json:"Title"`
	Extra                      map[string]interface{}
}
